spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-b676274db03340a19ae435c694dca7e1
      chat:
        options:
          model: qwen-plus
  datasource:
    url: jdbc:postgresql://rm-cn-fhh4a330g000112o.rwlb.rds.aliyuncs.com:5432/ai-agent?sslmode=disable
    username: db_user
    password: Wenzekai123